homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}

contact:
    path: /contact
    defaults: {_controller: AppBundle:Default:contact}

test:
    path: /test
    defaults: {_controller: AppBundle:Default:mailCheck}